spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://root:KLeuvUYVEVKkGqsNdiJjGoamTEANXDoY@acela.proxy.rlwy.net:25890/railway
    username: root
    password: KLeuvUYVEVKkGqsNdiJjGoamTEANXDoY
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
